// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/gitjob/pkg/generated/controllers/gitjob.cattle.io/v1 (interfaces: GitJobCache)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/rancher/gitjob/pkg/apis/gitjob.cattle.io/v1"
	v10 "github.com/rancher/gitjob/pkg/generated/controllers/gitjob.cattle.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
)

// MockGitJobCache is a mock of GitJobCache interface.
type MockGitJobCache struct {
	ctrl     *gomock.Controller
	recorder *MockGitJobCacheMockRecorder
}

// MockGitJobCacheMockRecorder is the mock recorder for MockGitJobCache.
type MockGitJobCacheMockRecorder struct {
	mock *MockGitJobCache
}

// NewMockGitJobCache creates a new mock instance.
func NewMockGitJobCache(ctrl *gomock.Controller) *MockGitJobCache {
	mock := &MockGitJobCache{ctrl: ctrl}
	mock.recorder = &MockGitJobCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitJobCache) EXPECT() *MockGitJobCacheMockRecorder {
	return m.recorder
}

// AddIndexer mocks base method.
func (m *MockGitJobCache) AddIndexer(arg0 string, arg1 v10.GitJobIndexer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddIndexer", arg0, arg1)
}

// AddIndexer indicates an expected call of AddIndexer.
func (mr *MockGitJobCacheMockRecorder) AddIndexer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndexer", reflect.TypeOf((*MockGitJobCache)(nil).AddIndexer), arg0, arg1)
}

// Get mocks base method.
func (m *MockGitJobCache) Get(arg0, arg1 string) (*v1.GitJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v1.GitJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGitJobCacheMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGitJobCache)(nil).Get), arg0, arg1)
}

// GetByIndex mocks base method.
func (m *MockGitJobCache) GetByIndex(arg0, arg1 string) ([]*v1.GitJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIndex", arg0, arg1)
	ret0, _ := ret[0].([]*v1.GitJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIndex indicates an expected call of GetByIndex.
func (mr *MockGitJobCacheMockRecorder) GetByIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIndex", reflect.TypeOf((*MockGitJobCache)(nil).GetByIndex), arg0, arg1)
}

// List mocks base method.
func (m *MockGitJobCache) List(arg0 string, arg1 labels.Selector) ([]*v1.GitJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*v1.GitJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGitJobCacheMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGitJobCache)(nil).List), arg0, arg1)
}
